"""
Django settings for PageGlow project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Используем деньюю версию python-decouple
try:
    from decouple import config
except ImportError:
    from os import getenv as config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Создать директории если их нет
for directory in ['logs', 'cache', 'static', 'media']:
    dir_path = os.path.join(BASE_DIR, directory)
    os.makedirs(dir_path, exist_ok=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG') 

ALLOWED_HOSTS = ["localhost","127.0.0.1","flachub.ru","www.flachub.ru" ]

INTERNAL_IPS = ["127.0.0.1"]

# Отключаем debug_toolbar для ASGI (daphne)
import sys
IS_ASGI = 'daphne' in sys.argv[0] or 'uvicorn' in sys.argv[0]

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = ['http://localhost:3000']

# # ===== SENTRY =====
# SENTRY_DSN = config('SENTRY_DSN', default='')

# if SENTRY_DSN:
#     import sentry_sdk
#     sentry_sdk.init(
#         dsn=SENTRY_DSN,
#         integrations=[
#             # Django integration
#         ],
#         traces_sample_rate=0.1,  # 10% транзакций
#         profiles_sample_rate=0.1,  # 10% профилей
#         environment=config('SENTRY_ENVIRONMENT', default='development'),
#         release=config('SENTRY_RELEASE', default='unknown'),
#     )

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'main.apps.MainConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_ckeditor_5',
    'rest_framework',
    'djoser',
    'meta',

    'django.contrib.sites',
    'django.contrib.sitemaps',

    # WebSocket / Channels
    'channels',

    # Backup
    'dbbackup',
]

# Отключаем debug_toolbar для ASGI
if not IS_ASGI:
    INSTALLED_APPS.insert(8, 'debug_toolbar')

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Отключаем debug_toolbar middleware для ASGI
if not IS_ASGI:
    MIDDLEWARE.insert(7, 'debug_toolbar.middleware.DebugToolbarMiddleware')


SITE_ID = 1

ROOT_URLCONF = 'PageGlow.urls'

TEMPLATES = [
    {
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend', 'build'),
            BASE_DIR / 'templates',
        ],

        'BACKEND': 'django.template.backends.django.DjangoTemplates',


        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.get_main_context',
                'main.context_processors.sidebar_context',
            ],
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main', 'static'),
]


WSGI_APPLICATION = 'PageGlow.wsgi.application'
ASGI_APPLICATION = 'PageGlow.asgi.application'

# Channels / WebSocket
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')],
#         },
#     },
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USERNAME'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'users:login'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'users.authentication.EmailAuthBackend',
)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = int(config('EMAIL_PORT', default='465'))
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

AUTH_USER_MODEL = 'users.User'

DEFAULT_USER_IMAGE = MEDIA_URL + 'users/default.png'

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

# CKEditor 5 настройки
customColorPalette = [
    {
        'color': '#hsl(0, 75%, 60%)',
        'label': 'Red'
    },
    {
        'color': '#hsl(120, 75%, 60%)',
        'label': 'Green'
    },
    {
        'color': '#hsl(240, 75%, 60%)',
        'label': 'Blue'
    },
]

# Настройка загрузки файлов для django_ckeditor_5
DJANGO_CKEDITOR_5_FILE_UPLOAD_PERMISSION = 'authenticated'
CKEDITOR_5_FILE_UPLOAD_PATH = 'ckeditor/uploads/'

# Типы файлов для загрузки
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'ico', 'svg', 'webm', 'mp4']

# Отключаем встроенный upload и используем кастомный
CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'ru-RU',
        'htmlSupport': {
            'allowAttributes': {
                '*': {
                    'classes': True,
                    'styles': True
                }
            }
        },
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
        },
        'placeholder': 'Заголовок',
    },
    'code_mode': {
        'toolbar': ['codeBlock', '|', 'undo', 'redo'],
        'codeBlock': {
            'languages': [
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'typescript', 'label': 'TypeScript'},
                {'language': 'java', 'label': 'Java'},
                {'language': 'cpp', 'label': 'C++'},
                {'language': 'go', 'label': 'Go'},
                {'language': 'rust', 'label': 'Rust'},
            ]
        }
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': [
                'heading', '|',
                'outdent', 'indent', '|',
                'bold', 'italic', 'link', 'underline', 'strikethrough',
                'code','subscript', 'superscript', 'highlight', '|',
                'codeBlock', 'sourceEditing', '|',
                'insertImage', 'mediaEmbed', '|',
                'bulletedList', 'numberedList', 'todoList', '|',
                'blockQuote', '|',
                'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
                'insertTable', 'horizontalLine', '|',
                'undo', 'redo', '|',
                'removeFormat'
            ],
            'shouldNotGroupWhenFull': True,
            'shouldStayGrouped': False
        },
        'language': 'ru-RU',
        # Счетчик слов и символов
        'wordCount': {
            'displayWords': True,
            'displayCharacters': True,
            'displayPages': False,
            'countNestedLists': True,
            'countHTML': False,
            'updateOnDestroy': True
        },
        # Настройки изображений
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft',
                'imageStyle:alignRight',
                'imageStyle:alignCenter',
                'imageStyle:side', '|',
                'resizeImage:50',
                'resizeImage:75',
                'resizeImage:100',
                'resizeImage:original'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ],
            'insert': {
                'type': 'auto'
            },
            'upload': {
                'multiple': True
            }
        },
        # Настройки таблиц
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        # Настройки заголовков
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Обычный текст', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Заголовок 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Заголовок 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Заголовок 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Заголовок 4', 'class': 'ck-heading_heading4' }
            ]
        },
        # Настройки кода
        'codeBlock': {
            'languages': [
                {'language': 'plaintext', 'label': 'Plain text'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'typescript', 'label': 'TypeScript'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'bash', 'label': 'Bash/Shell'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'java', 'label': 'Java'},
                {'language': 'cpp', 'label': 'C++'},
                {'language': 'csharp', 'label': 'C#'},
                {'language': 'go', 'label': 'Go'},
                {'language': 'rust', 'label': 'Rust'},
                {'language': 'php', 'label': 'PHP'},
                {'language': 'ruby', 'label': 'Ruby'},
                {'language': 'swift', 'label': 'Swift'},
                {'language': 'kotlin', 'label': 'Kotlin'},
            ]
        },
        # Подсветка синтаксиса
        'highlight': {
            'options': [
                {
                    'model': 'default',
                    'title': 'Default',
                    'class': 'ck-highlighted-text_default'
                },
                {
                    'model': 'marker',
                    'title': 'Маркер',
                    'class': 'ck-highlighted-text_marker'
                },
                {
                    'model': 'pen',
                    'title': 'Текст',
                    'class': 'ck-highlighted-text_pen'
                }
            ]
        },
        # Шрифты
        'fontSize': {
            'options': [8, 10, 12, 14, 'default', 18, 20, 22, 24, 26, 28, 36, 48]
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Georgia, serif',
                'Times New Roman, serif',
                'Courier New, monospace',
                'Verdana, sans-serif',
                'Tahoma, sans-serif',
                'Trebuchet MS, sans-serif'
            ]
        },
        # Плейсхолдер
        'placeholder': 'Начните писать вашу статью здесь... Используйте Markdown для форматирования кода: ```python код ```',
        # Список задач
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True
            }
        }
    }
}

# Дополнительные плагины CKEditor 5

DJOSER = {
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SEND_ACTIVATION_EMAIL': True,
    'SET_PASSWORD_RETYPE': True,
    'TOKEN_MODEL': None,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'ACTIVATION_URL': 'auth/verify/{uid}/{token}'
}

# Кэширование - используем Redis если доступен, иначе файловое
# CACHE_BACKEND = config('CACHE_BACKEND', default='filebased')

# if CACHE_BACKEND == 'redis':
#     CACHES = {
#         'default': {
#             'BACKEND': 'django_redis.cache.RedisCache',
#             'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/0'),
#             'OPTIONS': {
#                 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#                 'PARSER_KWARGS': {'encoding': 'utf8'},
#                 'CONNECTION_POOL_KWARGS': {'max_connections': 50, 'retry_on_timeout': True}
#             },
#             'KEY_PREFIX': 'flakhub',
#             'TIMEOUT': 300,
#         }
#     }
# else:
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#             'LOCATION': os.path.join(BASE_DIR, 'cache'),
#             'TIMEOUT': 300,
#         }
#     }

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 259200  
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000').split(',')

# Security headers
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net"),
    'style-src': ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net"),
    'img-src': ("'self'", "data:", "https:"),
    'font-src': ("'self'", "data:", "https:"),
    'connect-src': ("'self'",),
    'frame-ancestors': ("'none'",),
}

# If not in DEBUG mode, enforce HTTPS
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

META_SITE_PROTOCOL = 'https' if not DEBUG else 'http'
META_SITE_DOMAIN = config('META_SITE_DOMAIN', default='flakhub.ru')
META_SITE_TYPE = 'website'
META_SITE_NAME = 'ФлакХаб'
META_INCLUDE_KEYWORDS = ['статьи', 'информация', 'рекомендации', 'руководства']
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ===== DBBACKUP =====
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR, 'backups')}
DBBACKUP_CONNECTORS = {
    'default': {
        'SINGLE_TRANSACTION': True,
        'IF_EXISTS': True,
    }
}
DBBACKUP_CLEANUP_KEEP = 7  # Хранить 7 последних бэкапов
DBBACKUP_CLEANUP_KEEP_MEDIA = 7

# ===== SENTRY =====
SENTRY_DSN = config('SENTRY_DSN', default='')

if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[],
        traces_sample_rate=0.1,
        profiles_sample_rate=0.1,
        environment=config('SENTRY_ENVIRONMENT', default='development'),
        release=config('SENTRY_RELEASE', default='unknown'),
    )