# Generated by Django 6.0.2 on 2026-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_bid_chatmessage_companyprofile_dispute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-is_popular', 'category', 'name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, help_text='Краткое описание навыка', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Показывать в списке популярных навыков'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Язык программирования'), ('framework', 'Фреймворк'), ('tool', 'Инструмент'), ('database', 'База данных'), ('design', 'Дизайн'), ('mobile', 'Мобильная разработка'), ('devops', 'DevOps / Infrastructure'), ('testing', 'Тестирование'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS класс иконки (например: fab fa-python или fas fa-database)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_popular'], name='marketplace_categor_72f500_idx'),
        ),
    ]
