# Generated by Django 6.0.2 on 2026-03-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_skill_options_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='years_experience',
            field=models.CharField(choices=[('junior', 'До 1 года'), ('junior_plus', 'От 1 до 3 лет'), ('middle', 'От 3 до 6 лет'), ('senior', 'От 6 до 10 лет'), ('lead', 'Более 10 лет')], default='junior', help_text='Уровень опыта работы', max_length=20),
        ),
    ]
