# Generated by Django 6.0.2 on 2026-03-10 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_freelancerprofile_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Почасовая ставка в рублях', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
