# Generated by Django 6.0.2 on 2026-03-15 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_freelancerprofile_hourly_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_delivered',
            field=models.BooleanField(default=True, help_text='Сообщение доставлено'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Сообщение прочитано'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Время прочтения', null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='marketplace_is_read_8fb535_idx'),
        ),
    ]
