# Generated by Django 6.0.2 on 2026-03-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscriptions'),
        ('users', '0004_user_about_me'),
    ]

    operations = [
    ]
