# Generated by Django 6.0.2 on 2026-03-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_namber'),
    ]

    operations = [
    ]
