# Generated by Django 6.0.2 on 2026-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20260324_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_namber',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер телефона'),
        ),
    ]
