# Generated by Django 6.0.2 on 2026-03-27 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_notification_notification_type'),
        ('users', '0009_alter_user_phone_namber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название уровня')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('min_reputation', models.IntegerField(verbose_name='Минимальная репутация')),
                ('icon', models.CharField(default='🌱', max_length=50, verbose_name='Иконка (emoji)')),
                ('color', models.CharField(default='#999999', max_length=20, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('can_create_tags', models.BooleanField(default=False, verbose_name='Создание тегов')),
                ('can_edit_own_posts_longer', models.BooleanField(default=False, verbose_name='Расширенное редактирование постов')),
                ('can_moderate_comments', models.BooleanField(default=False, verbose_name='Модерация комментариев')),
                ('daily_upload_limit', models.IntegerField(default=10, verbose_name='Дневной лимит загрузок')),
                ('auto_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_levels', to='main.userbadge', verbose_name='Автоматический бейдж')),
            ],
            options={
                'verbose_name': 'Уровень пользователя',
                'verbose_name_plural': 'Уровни пользователей',
                'ordering': ['min_reputation'],
                'indexes': [models.Index(fields=['min_reputation'], name='users_userl_min_rep_c34ef0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Изменение репутации')),
                ('reason', models.CharField(choices=[('post_created', 'Публикация поста'), ('post_liked', 'Лайк поста (автору)'), ('comment_created', 'Создание комментария'), ('comment_liked', 'Лайк комментария (автору)'), ('answer_accepted', 'Лучший ответ'), ('subscription_received', 'Подписка на автора'), ('penalty', 'Штраф (нарушение)'), ('manual', 'Ручное изменение')], max_length=50, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_logs', to='main.comment', verbose_name='Комментарий')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_logs', to='main.post', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог репутации',
                'verbose_name_plural': 'Логи репутации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userr_user_id_e86d3f_idx'), models.Index(fields=['reason'], name='users_userr_reason_2cec40_idx')],
            },
        ),
    ]
