# Generated by Django 6.0.2 on 2026-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userlevel_userreputationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_gradient_end',
            field=models.CharField(default='#764ba2', help_text='HEX цвет (например #764ba2)', max_length=20, verbose_name='Конечный цвет градиента баннера'),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_gradient_start',
            field=models.CharField(default='#0c6acf', help_text='HEX цвет (например #0c6acf)', max_length=20, verbose_name='Начальный цвет градиента баннера'),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Фоновое изображение баннера (приоритет над градиентом)', null=True, upload_to='users/banners/%Y/%m/%d/', verbose_name='Изображение баннера'),
        ),
    ]
