# Generated by Django 6.0.2 on 2026-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_set_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreputationlog',
            name='reason',
            field=models.CharField(choices=[('post_created', 'Публикация поста'), ('post_deleted', 'Удаление поста'), ('post_liked', 'Лайк поста (автору)'), ('comment_created', 'Создание комментария'), ('comment_liked', 'Лайк комментария (автору)'), ('answer_accepted', 'Лучший ответ'), ('subscription_received', 'Подписка на автора'), ('penalty', 'Штраф (нарушение)'), ('manual', 'Ручное изменение')], max_length=50, verbose_name='Причина'),
        ),
    ]
