# Generated by Django 6.0.2 on 2026-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userreputationlog_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=False, verbose_name='Показывать дату рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Показывать email'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Показывать телефон'),
        ),
    ]
