# Generated by Django 6.0.2 on 2026-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_privacy_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=True, verbose_name='Показывать дату рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Показывать email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Показывать телефон'),
        ),
    ]
