# Generated by Django 6.0.2 on 2026-03-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_comment_main_commen_post_id_a5ec46_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок темы')),
                ('content', models.TextField(blank=True, default='', max_length=2000, verbose_name='Описание вопроса')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано'), (True, 'Закрыто')], default=1, verbose_name='Опубликовано?')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='main.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='discussions', to='main.tagpost', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждения',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.discussion', verbose_name='Обсуждение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.discussioncomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий обсуждения',
                'verbose_name_plural': 'Комментарии обсуждений',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['-time_create'], name='main_discus_time_cr_3e36c3_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['is_published', '-time_create'], name='main_discus_is_publ_00dad5_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author'], name='main_discus_author__5aaed1_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['cat'], name='main_discus_cat_id_288768_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['discussion', 'created_at'], name='main_discus_discuss_8ebe94_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['author'], name='main_discus_author__9c2bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['is_active'], name='main_discus_is_acti_97ae38_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['parent'], name='main_discus_parent__89ff66_idx'),
        ),
    ]
