# Generated by Django 6.0.2 on 2026-03-14 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_discussion_discussioncomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='discussion_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
