# Generated by Django 6.0.2 on 2026-03-14 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_discussion_favorites_discussion_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='discussion_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
