# Generated by Django 6.0.2 on 2026-03-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_social_features'),
    ]

    operations = [
        # Поле post_type уже добавлено в БД вручную, просто синхронизируем миграции
    ]
