# Generated by Django 6.0.2 on 2026-03-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_comment_is_edited_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Комментарий'), ('follow', 'Подписка'), ('new_post', 'Новая статья'), ('achievement', 'Достижение')], max_length=20),
        ),
    ]
