# Generated by Django 6.0.2 on 2026-06-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=0, verbose_name='Опубликовать?'),
        ),
    ]
