# Generated by Django 6.0.6 on 2026-07-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chat'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Комментарий'), ('follow', 'Подписка'), ('new_post', 'Новая статья'), ('achievement', 'Достижение'), ('chat_message', 'Сообщение')], max_length=20),
        ),
    ]
